### PR TITLE
DEV-31192: Fixed injection abilities

### PR DESCRIPTION
**Pull request by alexpalchuk**
According to best practices for xml parsing added disabling injections

### CODE REVIEW

**Review by DanMelman — APPROVED** [review]
LGTM!

**Comment by barakm** [comment]
@alexpalchuk I think we need another test that validated remote resource loading (over HTTP) along with the file system based one.

**Comment by alexpalchuk** [comment]
> @alexpalchuk I think we need another test that validated remote resource loading (over HTTP) along with the file system based one.

ok, will add it

**Comment by alexpalchuk** [comment]
> @alexpalchuk I think we need another test that validated remote resource loading (over HTTP) along with the file system based one.

added in https://github.com/logzio/sawmill/pull/300

**Pull request merged**
